version: '2'
services:
  talina-web:
    container_name: talina-web
    image: justckr/ubuntu-nginx-php:php7.2
    env_file:
      - ../.env
    environment:
      VIRTUAL_HOST: api.talina.local
      MINIO_ENDPOINT: http://store-minio:9000
      APP_URL: http://api.talina.local
      SCHOOL_CODE: SCHOOL01
    ports:
      - "8080:80"
    volumes:
      - ../:/app/src/
    hostname: api.talina.local
    networks:
      - talina
  talina-db:
    container_name: talina-db
    image: mysql:5.7
    env_file:
      - ../.env
    ports:
      - 3306
    volumes:
      - talina-db-data:/databases
      - talina-db-data:/var/lib/mysql
      - ./mysql:/etc/mysql/mysql.conf.d
    networks:
      - talina

  talina-nginx:
    container_name: talina-nginx
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/ssl:/etc/nginx/certs
      - ./nginx/nginx.conf:/etc/nginx/proxy.conf:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d:ro
      - ./nginx/dhparam:/etc/nginx/dhparam/
    networks:
      talina:
        aliases:
          - minio.talina.local
          - api.talina.local

  talina-minio:
    container_name: talina-minio
    image: vhenjoseph/minio:latest
    environment:
      VIRTUAL_HOST: minio.talina.local
      VIRTUAL_PORT: 9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: myminiosecret
      MINIO_REGION: itmattersnot
    ports:
       - "9001:9000"
    volumes:
      - talina-minio-data:/minio/data
      - talina-minio-config:/minio/config
    networks:
      - talina

volumes:
  talina-db-data:
    external: true
  talina-minio-data:
    external: true
  talina-minio-config:
    external: true

networks:
  talina:
    external: true
