version: '2'
services:
  schoolhub-web:
    container_name: schoolhub-web
    image: justckr/ubuntu-nginx-php:php7.2
    env_file:
      - ../.env
    environment:
      - VIRTUAL_HOST=schoolhub.local
    ports:
      - "8080:80"
    volumes:
      - ../:/app/src/
    hostname: schoolhub.local
    networks:
      - schoolhub
  schoolhub-db:
    container_name: schoolhub-db
    image: mysql:5.7
    env_file:
      - ../.env
    ports:
      - 3306
    volumes:
      - schoolhub-db-data:/databases
      - schoolhub-db-data:/var/lib/mysql
      - ./mysql:/etc/mysql/mysql.conf.d
    networks:
      - schoolhub

volumes:
  schoolhub-db-data:
    external: true

networks:
  schoolhub:
    external: true
