<?php

use Illuminate\Database\Seeder;

class Data_rowsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     *
     * @throws Exception
     */
    public function run()
    {
     try {
        \DB::beginTransaction();

        \DB::table('data_rows')->delete();

        \DB::table('data_rows')->insert(array (
                0 => 
                array (
                    'id' => 1,
                    'data_type_id' => 1,
                    'field' => 'id',
                    'type' => 'number',
                    'display_name' => 'ID',
                    'required' => 1,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 1,
                ),
                1 => 
                array (
                    'id' => 3,
                    'data_type_id' => 1,
                    'field' => 'email',
                    'type' => 'text',
                    'display_name' => 'Email',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 3,
                ),
                2 => 
                array (
                    'id' => 4,
                    'data_type_id' => 1,
                    'field' => 'password',
                    'type' => 'password',
                    'display_name' => 'Password',
                    'required' => 1,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 5,
                ),
                3 => 
                array (
                    'id' => 5,
                    'data_type_id' => 1,
                    'field' => 'remember_token',
                    'type' => 'text',
                    'display_name' => 'Remember Token',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 7,
                ),
                4 => 
                array (
                    'id' => 6,
                    'data_type_id' => 1,
                    'field' => 'created_at',
                    'type' => 'timestamp',
                    'display_name' => 'Created At',
                    'required' => 1,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 8,
                ),
                5 => 
                array (
                    'id' => 7,
                    'data_type_id' => 1,
                    'field' => 'updated_at',
                    'type' => 'timestamp',
                    'display_name' => 'Updated At',
                    'required' => 1,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 10,
                ),
                6 => 
                array (
                    'id' => 8,
                    'data_type_id' => 1,
                    'field' => 'avatar',
                    'type' => 'image',
                    'display_name' => 'Avatar',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 2,
                ),
                7 => 
                array (
                    'id' => 9,
                    'data_type_id' => 1,
                    'field' => 'user_belongsto_role_relationship',
                    'type' => 'relationship',
                    'display_name' => 'Role',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 0,
                    'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"display_name","pivot_table":"roles","pivot":"0","taggable":"0"}',
                    'order' => 15,
                ),
                8 => 
                array (
                    'id' => 10,
                    'data_type_id' => 1,
                    'field' => 'user_belongstomany_role_relationship',
                    'type' => 'relationship',
                    'display_name' => 'Roles',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 0,
                    'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsToMany","column":"id","key":"id","label":"display_name","pivot_table":"user_roles","pivot":"1","taggable":"0"}',
                    'order' => 16,
                ),
                9 => 
                array (
                    'id' => 11,
                    'data_type_id' => 1,
                    'field' => 'settings',
                    'type' => 'hidden',
                    'display_name' => 'Settings',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 17,
                ),
                10 => 
                array (
                    'id' => 12,
                    'data_type_id' => 2,
                    'field' => 'id',
                    'type' => 'number',
                    'display_name' => 'ID',
                    'required' => 1,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => NULL,
                    'order' => 1,
                ),
                11 => 
                array (
                    'id' => 13,
                    'data_type_id' => 2,
                    'field' => 'name',
                    'type' => 'text',
                    'display_name' => 'Name',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => NULL,
                    'order' => 2,
                ),
                12 => 
                array (
                    'id' => 14,
                    'data_type_id' => 2,
                    'field' => 'created_at',
                    'type' => 'timestamp',
                    'display_name' => 'Created At',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => NULL,
                    'order' => 3,
                ),
                13 => 
                array (
                    'id' => 15,
                    'data_type_id' => 2,
                    'field' => 'updated_at',
                    'type' => 'timestamp',
                    'display_name' => 'Updated At',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => NULL,
                    'order' => 4,
                ),
                14 => 
                array (
                    'id' => 16,
                    'data_type_id' => 3,
                    'field' => 'id',
                    'type' => 'number',
                    'display_name' => 'ID',
                    'required' => 1,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => NULL,
                    'order' => 1,
                ),
                15 => 
                array (
                    'id' => 17,
                    'data_type_id' => 3,
                    'field' => 'name',
                    'type' => 'text',
                    'display_name' => 'Name',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => NULL,
                    'order' => 2,
                ),
                16 => 
                array (
                    'id' => 18,
                    'data_type_id' => 3,
                    'field' => 'created_at',
                    'type' => 'timestamp',
                    'display_name' => 'Created At',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => NULL,
                    'order' => 3,
                ),
                17 => 
                array (
                    'id' => 19,
                    'data_type_id' => 3,
                    'field' => 'updated_at',
                    'type' => 'timestamp',
                    'display_name' => 'Updated At',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => NULL,
                    'order' => 4,
                ),
                18 => 
                array (
                    'id' => 20,
                    'data_type_id' => 3,
                    'field' => 'display_name',
                    'type' => 'text',
                    'display_name' => 'Display Name',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => NULL,
                    'order' => 5,
                ),
                19 => 
                array (
                    'id' => 21,
                    'data_type_id' => 1,
                    'field' => 'role_id',
                    'type' => 'text',
                    'display_name' => 'Role',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 14,
                ),
                20 => 
                array (
                    'id' => 22,
                    'data_type_id' => 4,
                    'field' => 'id',
                    'type' => 'text',
                    'display_name' => 'Id',
                    'required' => 1,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 1,
                ),
                21 => 
                array (
                    'id' => 23,
                    'data_type_id' => 4,
                    'field' => 'school_code',
                    'type' => 'text',
                    'display_name' => 'School Code',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 3,
                ),
                22 => 
                array (
                    'id' => 24,
                    'data_type_id' => 4,
                    'field' => 'school_name',
                    'type' => 'text',
                    'display_name' => 'Name',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 4,
                ),
                23 => 
                array (
                    'id' => 25,
                    'data_type_id' => 4,
                    'field' => 'school_logo',
                    'type' => 'image',
                    'display_name' => 'Logo',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 2,
                ),
                24 => 
                array (
                    'id' => 26,
                    'data_type_id' => 4,
                    'field' => 'address_line_1',
                    'type' => 'text',
                    'display_name' => 'Address Line 1',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 5,
                ),
                25 => 
                array (
                    'id' => 27,
                    'data_type_id' => 4,
                    'field' => 'address_line_2',
                    'type' => 'text',
                    'display_name' => 'Address Line 2',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 6,
                ),
                26 => 
                array (
                    'id' => 28,
                    'data_type_id' => 4,
                    'field' => 'address_city',
                    'type' => 'text',
                    'display_name' => 'Address City',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 7,
                ),
                27 => 
                array (
                    'id' => 29,
                    'data_type_id' => 4,
                    'field' => 'address_country',
                    'type' => 'text',
                    'display_name' => 'Address Country',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 8,
                ),
                28 => 
                array (
                    'id' => 30,
                    'data_type_id' => 4,
                    'field' => 'phone_number',
                    'type' => 'text',
                    'display_name' => 'Phone Number',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 9,
                ),
                29 => 
                array (
                    'id' => 31,
                    'data_type_id' => 4,
                    'field' => 'created_at',
                    'type' => 'timestamp',
                    'display_name' => 'Created At',
                    'required' => 1,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 10,
                ),
                30 => 
                array (
                    'id' => 32,
                    'data_type_id' => 4,
                    'field' => 'updated_at',
                    'type' => 'timestamp',
                    'display_name' => 'Updated At',
                    'required' => 1,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 11,
                ),
                31 => 
                array (
                    'id' => 33,
                    'data_type_id' => 4,
                    'field' => 'created_by',
                    'type' => 'text',
                    'display_name' => 'Created By',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 12,
                ),
                32 => 
                array (
                    'id' => 34,
                    'data_type_id' => 4,
                    'field' => 'updated_by',
                    'type' => 'text',
                    'display_name' => 'Updated By',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 13,
                ),
                33 => 
                array (
                    'id' => 35,
                    'data_type_id' => 4,
                    'field' => 'deleted_at',
                    'type' => 'timestamp',
                    'display_name' => 'Deleted At',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 14,
                ),
                34 => 
                array (
                    'id' => 36,
                    'data_type_id' => 6,
                    'field' => 'id',
                    'type' => 'text',
                    'display_name' => 'Id',
                    'required' => 1,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 1,
                ),
                35 => 
                array (
                    'id' => 37,
                    'data_type_id' => 6,
                    'field' => 'name',
                    'type' => 'text',
                    'display_name' => 'Name',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 6,
                ),
                36 => 
                array (
                    'id' => 38,
                    'data_type_id' => 6,
                    'field' => 'description',
                    'type' => 'text',
                    'display_name' => 'Description',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 7,
                ),
                37 => 
                array (
                    'id' => 39,
                    'data_type_id' => 6,
                    'field' => 'room_number',
                    'type' => 'text',
                    'display_name' => 'Room Number',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 8,
                ),
                38 => 
                array (
                    'id' => 40,
                    'data_type_id' => 6,
                    'field' => 'teacher_id',
                    'type' => 'text',
                    'display_name' => 'Teacher Id',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 2,
                ),
                39 => 
                array (
                    'id' => 41,
                    'data_type_id' => 6,
                    'field' => 'subject_id',
                    'type' => 'text',
                    'display_name' => 'Subject Id',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 3,
                ),
                40 => 
                array (
                    'id' => 42,
                    'data_type_id' => 6,
                    'field' => 'created_by',
                    'type' => 'text',
                    'display_name' => 'Created By',
                    'required' => 1,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 9,
                ),
                41 => 
                array (
                    'id' => 43,
                    'data_type_id' => 6,
                    'field' => 'updated_by',
                    'type' => 'text',
                    'display_name' => 'Updated By',
                    'required' => 1,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 10,
                ),
                42 => 
                array (
                    'id' => 44,
                    'data_type_id' => 6,
                    'field' => 'year_id',
                    'type' => 'text',
                    'display_name' => 'Year Id',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 4,
                ),
                43 => 
                array (
                    'id' => 45,
                    'data_type_id' => 6,
                    'field' => 'section_id',
                    'type' => 'text',
                    'display_name' => 'Section Id',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 5,
                ),
                44 => 
                array (
                    'id' => 46,
                    'data_type_id' => 6,
                    'field' => 'color',
                    'type' => 'text',
                    'display_name' => 'Color',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 11,
                ),
                45 => 
                array (
                    'id' => 47,
                    'data_type_id' => 6,
                    'field' => 'image',
                    'type' => 'text',
                    'display_name' => 'Image',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 12,
                ),
                46 => 
                array (
                    'id' => 48,
                    'data_type_id' => 6,
                    'field' => 'date_from',
                    'type' => 'text',
                    'display_name' => 'Date From',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 13,
                ),
                47 => 
                array (
                    'id' => 49,
                    'data_type_id' => 6,
                    'field' => 'date_to',
                    'type' => 'text',
                    'display_name' => 'Date To',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 14,
                ),
                48 => 
                array (
                    'id' => 50,
                    'data_type_id' => 6,
                    'field' => 'time_from',
                    'type' => 'text',
                    'display_name' => 'Time From',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 15,
                ),
                49 => 
                array (
                    'id' => 51,
                    'data_type_id' => 6,
                    'field' => 'time_to',
                    'type' => 'text',
                    'display_name' => 'Time To',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 16,
                ),
                50 => 
                array (
                    'id' => 52,
                    'data_type_id' => 6,
                    'field' => 'frequency',
                    'type' => 'text',
                    'display_name' => 'Frequency',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 17,
                ),
                51 => 
                array (
                    'id' => 53,
                    'data_type_id' => 6,
                    'field' => 'created_at',
                    'type' => 'timestamp',
                    'display_name' => 'Created At',
                    'required' => 1,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 18,
                ),
                52 => 
                array (
                    'id' => 54,
                    'data_type_id' => 6,
                    'field' => 'updated_at',
                    'type' => 'timestamp',
                    'display_name' => 'Updated At',
                    'required' => 1,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 19,
                ),
                53 => 
                array (
                    'id' => 55,
                    'data_type_id' => 6,
                    'field' => 'deleted_at',
                    'type' => 'timestamp',
                    'display_name' => 'Deleted At',
                    'required' => 0,
                    'browse' => 0,
                    'read' => 0,
                    'edit' => 0,
                    'add' => 0,
                    'delete' => 0,
                    'details' => '{}',
                    'order' => 20,
                ),
                54 => 
                array (
                    'id' => 56,
                    'data_type_id' => 1,
                    'field' => 'username',
                    'type' => 'text',
                    'display_name' => 'Username',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 4,
                ),
                55 => 
                array (
                    'id' => 57,
                    'data_type_id' => 1,
                    'field' => 'user_type',
                    'type' => 'text',
                    'display_name' => 'User Type',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 6,
                ),
                56 => 
                array (
                    'id' => 58,
                    'data_type_id' => 1,
                    'field' => 'first_name',
                    'type' => 'text',
                    'display_name' => 'First Name',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 9,
                ),
                57 => 
                array (
                    'id' => 59,
                    'data_type_id' => 1,
                    'field' => 'middle_name',
                    'type' => 'text',
                    'display_name' => 'Middle Name',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 11,
                ),
                58 => 
                array (
                    'id' => 60,
                    'data_type_id' => 1,
                    'field' => 'last_name',
                    'type' => 'text',
                    'display_name' => 'Last Name',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 12,
                ),
                59 => 
                array (
                    'id' => 61,
                    'data_type_id' => 1,
                    'field' => 'gender',
                    'type' => 'text',
                    'display_name' => 'Gender',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 13,
                ),
                60 => 
                array (
                    'id' => 62,
                    'data_type_id' => 1,
                    'field' => 'phone_number',
                    'type' => 'text',
                    'display_name' => 'Phone Number',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 18,
                ),
                61 => 
                array (
                    'id' => 63,
                    'data_type_id' => 1,
                    'field' => 'school_id',
                    'type' => 'text',
                    'display_name' => 'School Id',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 19,
                ),
                62 => 
                array (
                    'id' => 64,
                    'data_type_id' => 1,
                    'field' => 'status',
                    'type' => 'text',
                    'display_name' => 'Status',
                    'required' => 1,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 20,
                ),
                63 => 
                array (
                    'id' => 65,
                    'data_type_id' => 1,
                    'field' => 'deleted_at',
                    'type' => 'timestamp',
                    'display_name' => 'Deleted At',
                    'required' => 0,
                    'browse' => 1,
                    'read' => 1,
                    'edit' => 1,
                    'add' => 1,
                    'delete' => 1,
                    'details' => '{}',
                    'order' => 21,
                ),
            ));
       } catch(Exception $e) {
         throw new Exception('Exception occur ' . $e);

         \DB::rollBack();
       }

       \DB::commit();
    }
}
