name: Laravel

on:
  push:
    branches: [ master ]
    
jobs:
  laravel-tests:
    runs-on: ubuntu-latest  
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: no
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testdb
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.2']
    steps:
    - uses: actions/checkout@v2
    - name: Create storage directories
      run: mkdir -p storage/framework/{sessions,views,cache} && chmod -R 777 storage/framework
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Start mysql service
      run: sudo /etc/init.d/mysql start
    - name: Run Migration
      run: php artisan migrate:fresh
      env:
        DB_PORT: ${{ job.services.mysql.ports['3306'] }}
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit
      env:
        DB_PORT: ${{ job.services.mysql.ports['3306'] }}
    - name: Github Action Notification
      uses: 8398a7/action-slack@v3
      with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow # selectable (default: repo,message)
      env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: always() # Pick up events even if the job fails or is canceled.
